### ISSUE TITLE
Merge with openfda-R?

### ISSUE THREAD

**Issue by rjpower** [leeper/openfda#1]
As part of a recent openfda-athon, I ended up writing a (different) R interface to the openfda.

I noticed your package is a bit incomplete at the moment, so it seems like it would make sense to join forces: let me know if you'd be interested in reforking based on my repo (https://github.com/rjpower/openfda-R) or if you have ideas for changes/extensions.

Cheers,
R

**Comment by leeper** [comment]
@rjpower Great! I never really got around to work on this, so I'm glad to see someone else did. How about you take the "openfda" package name (packages with hyphens in the name aren't allowed on CRAN, by the way) and I'll just delete this repo since it doesn't really have any substantive code.

I'd also talked to @daspringate about migrating this to rOpenHealth eventually, so maybe it would make sense to move your package there?

**Comment by DASpringate** [comment]
Would be good to have it on rOpenHealth if you are interested.  Good idea @leeper about the name change.  @rjpower Let me know and I can set you up with a temporary admin to transfer the repo and then put you both down as admins on the openfda package.

Transferring repos details:
https://help.github.com/articles/transferring-a-repository/

**Comment by rjpower** [comment]
I'd be happy to transfer it over (it's particularly a good time as I'll be
out of the country for a few months and won't be able to do much admin work
while I'm out).

**Comment by DASpringate** [comment]
Great! I've invited you both to the openfda group as admins.  @rjpower Can you rename the repo before you transfer over?

Let me know if you have any problems transferring...

**Comment by leeper** [comment]
Thanks!

On Wed, Mar 4, 2015 at 11:29 AM, David A Springate <notifications@github.com

**Comment by rjpower** [comment]
Okay, I think the move succeeded: https://github.com/ropenhealth/openfda

Thanks for all the quick responses!

**Comment by leeper** [comment]
Fantastic!
